run:
  skip-dirs:
    - pkg/uroot/test
    - cmds/core/elvish

linters:
  disable-all: true
  enable:
    - revive
    - ineffassign
    - staticcheck
    - stylecheck

linters-settings:
  staticcheck:
    checks: ["all", "-SA1006", "-SA1019", "-SA4006", "-SA9004"]
  stylecheck:
    checks: ["all", "-ST1003", "-ST1023"]

issues:
  exclude-rules:
    - linters: revive
      text: "don't use underscores"
    - linters: revive
      text: "don't use ALL_CAPS"
    - linters: revive
      text: "stutter"
    - linters: revive
      text: "unexported-return"
    - linters: revive
      text: "unused-parameter"
    - linters: revive
      text: "redefines-builtin-id"
    - linters: revive
      text: "superfluous-else"
    - linters: revive
      text: "empty-block"
