amd64:
  VMTEST_QEMU:
    container: "ghcr.io/hugelgupf/vmtest/qemu:main"
    template: "{{.qemu}}/bin/qemu-system-x86_64 -L {{.qemu}}/pc-bios -m 1G"
    directories:
      qemu: "/zqemu"

  VMTEST_KERNEL:
    container: "ghcr.io/u-root/u-root/test-kernel-amd64@sha256:3fa8c30357d6351a5e91e1f0cf6ed00368d56d98908a39e594c2dcfcd5f110c9"
    template: "{{.bzImage}}"
    files:
      bzImage: "/bzImage"

  UROOT_MULTIBOOT_TEST_KERNEL_DIR:
    container: "ghcr.io/u-root/u-root/test-multiboot-test-kernel-amd64@sha256:4439ae6289f5ccb5fa193556de8d639900c1a4c6f57c8d1d6015f5ea49b5d9f9"
    template: "{{.mbdir}}"
    directories:
      mbdir: "/mb"

  UROOT_TEST_UEFIPAYLOAD:
    container: "ghcr.io/u-root/u-root/test-uefipayload-amd64@sha256:0c8eb1b8a20b1ab3748b830eef76634711586f18ff0accf7ba98015fa86383ff"
    template: "{{.payload}}"
    files:
      payload: "/UEFIPAYLOAD.fd"

arm:
  VMTEST_QEMU:
    container: "ghcr.io/hugelgupf/vmtest/qemu:main"
    template: "{{.qemu}}/bin/qemu-system-arm -M virt,highmem=off -L {{.qemu}}/pc-bios"
    directories:
      qemu: "/zqemu"

  VMTEST_KERNEL:
    container: "ghcr.io/u-root/u-root/test-kernel-arm@sha256:b4f28a8c0766271dc2998b8836cbd22f1a7ddf3927109d87049124b5858a5cbe"
    template: "{{.zImage}}"
    files:
      zImage: "/zImage"

arm64:
  VMTEST_QEMU:
    container: "ghcr.io/hugelgupf/vmtest/qemu:main"
    template: "{{.qemu}}/bin/qemu-system-aarch64 -machine virt -cpu max -m 1G -L {{.qemu}}/pc-bios"
    directories:
      qemu: "/zqemu"

  VMTEST_KERNEL:
    container: "ghcr.io/u-root/u-root/test-kernel-arm64@sha256:2396e788e4cfb5689f4df27986f78f053befbe325aed4e9651910fe720b2d606"
    template: "{{.Image}}"
    files:
      Image: "/Image"
