amd64:
  VMTEST_QEMU:
    container: "ghcr.io/hugelgupf/vmtest/qemu:main"
    template: "{{.qemu}}/bin/qemu-system-x86_64 -L {{.qemu}}/pc-bios -m 1G"
    directories:
      qemu: "/zqemu"

  VMTEST_KERNEL:
    container: "ghcr.io/u-root/u-root/test-kernel-amd64@sha256:f27fc07be718df785b2ce4a21a6eece6daf0532f7c971cec279d84806b0f04c3"
    template: "{{.bzImage}}"
    files:
      bzImage: "/bzImage"

  UROOT_MULTIBOOT_TEST_KERNEL_DIR:
    container: "ghcr.io/u-root/u-root/test-multiboot-test-kernel-amd64@sha256:4439ae6289f5ccb5fa193556de8d639900c1a4c6f57c8d1d6015f5ea49b5d9f9"
    template: "{{.mbdir}}"
    directories:
      mbdir: "/mb"

  UROOT_TEST_UEFIPAYLOAD:
    container: "ghcr.io/u-root/u-root/test-uefipayload-amd64@sha256:0c8eb1b8a20b1ab3748b830eef76634711586f18ff0accf7ba98015fa86383ff"
    template: "{{.payload}}"
    files:
      payload: "/UEFIPAYLOAD.fd"

arm:
  VMTEST_QEMU:
    container: "ghcr.io/hugelgupf/vmtest/qemu:main"
    template: "{{.qemu}}/bin/qemu-system-arm -M virt,highmem=off -L {{.qemu}}/pc-bios"
    directories:
      qemu: "/zqemu"

  VMTEST_KERNEL:
    container: "ghcr.io/u-root/u-root/test-kernel-arm@sha256:9877321ee56df88e1cd9a19a3431d0952f27a997a5c182f66007ebc8b94df4e8"
    template: "{{.zImage}}"
    files:
      zImage: "/zImage"

arm64:
  VMTEST_QEMU:
    container: "ghcr.io/hugelgupf/vmtest/qemu:main"
    template: "{{.qemu}}/bin/qemu-system-aarch64 -machine virt -cpu max -m 1G -L {{.qemu}}/pc-bios"
    directories:
      qemu: "/zqemu"

  VMTEST_KERNEL:
    container: "ghcr.io/u-root/u-root/test-kernel-arm64@sha256:9e861fbab497a182c8397a34d371d6924ac65e8a3f044343d87f3cdfaa8ae4a4"
    template: "{{.Image}}"
    files:
      Image: "/Image"
