#!/bin/bash
set -e
# This README is also a script you can run to test this idea out.
# This is a root file system all based on Go. 
#
#The only binary is the builder, and 6?. The rest gets
#built dynamically into a ramdisk-mounted /.
#Some tools won't build if you build with CGO_ENABLED=0
#But we don't want to carry along a gcc dependency along with
#everything else.
#
#You can test with chroot.
#built dynamically into a ramdisk-mounted /.
#
#Then set (assuming you are in $HOME):
# Extract our go toolchain.
mkdir -p go
sudo mount -t tmpfs none go
cpio -id < go.cpio
OLDPATH=$PATH
export GOPATH=$HOME/u-root
export GOROOT=$HOME/u-root/go
PATH=$GOPATH/bin:$GOPATH/buildbin:$GOPATH/go/bin:$PATH
#
(GOBIN=`pwd`/buildbin go install installcommand)
# until we figure out the trickery to get sh to build dynamically, well ...
#(GOBIN=`pwd`/buildbin go install sh)
PATH=$OLDPATH
mkdir -p  bin tmp etc go/pkg/linux_amd64 tcz dev lib usr/lib
sudo mount -t tmpfs none bin
#sudo mount -t tmpfs none tmp
sudo mount -t tmpfs none etc
sudo mount -t tmpfs none tcz
sudo mount --bind /dev dev
set +e
cpio -i -E tinycorebase/filelist < tinycorebase/corepure64.cpio
set -e
#bash
cat /etc/resolv.conf > etc/resolv.conf
# The ultimate fallback.
echo nameserver 8.8.8.8 >> etc/resolv.conf
#export GOPATH=/
#export GOROOT=/go
#export GOBIN=/bin
#export PATH=$GOPATH/bin:$GOPATH/buildbin:$GOPATH/go/bin:$PATH
#echo $PATH
sudo chroot . /buildbin/sh
set +e
sudo umount tmp
sudo umount etc
sudo umount bin
sudo umount tcz
sudo umount go
sudo umount dev
sudo umount tmp/tcloop/*
#
#then type 
#date
#and watch how it goes.
#
#What happens: 
#finds date in $HOME/u-root/buildbin/date
#symlink to installcommand
#runs installcommand, installs date in $HOME/u-root/bin, 
#installcommand runs the command with arg.
#
#All subsequent invocations of date run the compiled version.
