all:
	latex Request-for-Comment-Process-for-u-root.tex
	bibtex Request-for-Comment-Process-for-u-root.aux
	latex Request-for-Comment-Process-for-u-root.tex
	bibtex Request-for-Comment-Process-for-u-root.aux
	latex Request-for-Comment-Process-for-u-root.tex

include ../Makefile.inc
