// Code generated by "stringer --type=EntryType"; DO NOT EDIT.

package diskboot

import "strconv"

const _EntryType_name = "ElfMultiboot"

var _EntryType_index = [...]uint8{0, 3, 12}

func (i EntryType) String() string {
	if i < 0 || i >= EntryType(len(_EntryType_index)-1) {
		return "EntryType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EntryType_name[_EntryType_index[i]:_EntryType_index[i+1]]
}
