#!/bin/bash
set -e
set +x
rm -rf tmp
mkdir tmp
cd tmp

mkdir -p dev etc usr/lib lib64 tmp bin tcz
echo nameserver 8.8.8.8 > etc/resolv.conf
cp /etc/localtime etc

rm -f dev/null
mknod dev/console c 5 1
mknod dev/null c 1 3
mknod dev/ttyS0  c 4 64
rsync -av /dev/loop* dev
cat /etc/resolv.conf > etc/resolv.conf
ls -lR dev
pwd

find . -print | cpio -H newc -o > ../dev.cpio

echo OK
rm -rf tmp
