name: Deploy Page
on:
  push:
    branches:
      - main
    paths:
      - 'website/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      - name: Install dependencies & build
        working-directory: ./website
        run: |
          npm install
          npm run production
      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          publish_dir: ./website/dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: u-root.org
