---
name: TinyGo regression test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: tinygo/tinygo-dev:sha-ec0a142190bd21ecefd91868f36df70e92e9ac2c
    steps:
      - name: Install actions dependencies into tinygo container (Debain)
        run: |
          apt-get update
          apt-get install -y nodejs
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
      - name: Run regression builder core
        run: |
          # the docker image adds tinygo to the path
          TINYGO=$(which tinygo)
          TINYGOVER=$($TINYGO version | awk {'print $3'})
          GOVER=$(go version | awk {'print $3'} )

          # fatal: detected dubious ownership in repository at '/__w/u-root/u-root'
          # To add an exception for this directory, call:
          git config --global --add safe.directory /__w/u-root/u-root          

          # $GITHUB_STEP_SUMMARY upload aborted, supports content up to a size 
          # of 1024k, got 1309k. For more information see:

          mkdir -p $PWD/out
          go run tools/tinygo-buildstatus/main.go \
              tools/tinygo-buildstatus/statusquo.go \
              -tinygo $TINYGO \
              -commit-tinygo $TINYGOVER \
              -commit-uroot $(git rev-parse HEAD) \
              -version-go $GOVER \
              -cmdout $PWD/out \
              cmds/core/* > $GITHUB_STEP_SUMMARY
      
      - name: Run regression builder exp
        run: |
          # the docker image adds tinygo to the path
          TINYGO=$(which tinygo)
          TINYGOVER=$($TINYGO version | awk {'print $3'})
          GOVER=$(go version | awk {'print $3'} )

          go run tools/tinygo-buildstatus/main.go \
              tools/tinygo-buildstatus/statusquo.go \
              -tinygo $TINYGO \
              -commit-tinygo $TINYGOVER \
              -commit-uroot $(git rev-parse HEAD) \
              -version-go $GOVER \
              cmds/exp/* > $GITHUB_STEP_SUMMARY